# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tela.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QButtonGroup, QCheckBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QSpinBox, QStatusBar, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1478, 736)
        MainWindow.setStyleSheet(u"background-color: rgb(195, 195, 195);\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 250, 121, 16))
        font = QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 170, 101, 16))
        self.label_10.setFont(font)
        self.inicio_1024 = QRadioButton(self.centralwidget)
        self.buttonGroup_2 = QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName(u"buttonGroup_2")
        self.buttonGroup_2.addButton(self.inicio_1024)
        self.inicio_1024.setObjectName(u"inicio_1024")
        self.inicio_1024.setGeometry(QRect(210, 20, 171, 20))
        self.inicio_1024.setFont(font)
        self.inicio_1024.setCheckable(True)
        self.inicio_1024.setChecked(False)
        self.radioButton_64 = QRadioButton(self.centralwidget)
        self.buttonGroup = QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(u"buttonGroup")
        self.buttonGroup.addButton(self.radioButton_64)
        self.radioButton_64.setObjectName(u"radioButton_64")
        self.radioButton_64.setGeometry(QRect(260, 280, 97, 20))
        self.radioButton_64.setFont(font)
        self.radioButton_64.setCheckable(True)
        self.inicio_0 = QRadioButton(self.centralwidget)
        self.buttonGroup_2.addButton(self.inicio_0)
        self.inicio_0.setObjectName(u"inicio_0")
        self.inicio_0.setGeometry(QRect(20, 20, 151, 20))
        self.inicio_0.setFont(font)
        self.Rede_pub = QLineEdit(self.centralwidget)
        self.Rede_pub.setObjectName(u"Rede_pub")
        self.Rede_pub.setGeometry(QRect(30, 200, 133, 22))
        self.Rede_pub.setFont(font)
        self.Regras_nat = QTextBrowser(self.centralwidget)
        self.Regras_nat.setObjectName(u"Regras_nat")
        self.Regras_nat.setGeometry(QRect(420, 370, 1041, 331))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(240, 90, 152, 16))
        self.label_8.setFont(font)
        self.Rede_priv = QLineEdit(self.centralwidget)
        self.Rede_priv.setObjectName(u"Rede_priv")
        self.Rede_priv.setGeometry(QRect(30, 120, 133, 22))
        self.Rede_priv.setFont(font)
        self.Rede_priv.setTabletTracking(False)
        self.Rede_priv.setAcceptDrops(False)
        self.Regras_jumping = QTextBrowser(self.centralwidget)
        self.Regras_jumping.setObjectName(u"Regras_jumping")
        self.Regras_jumping.setGeometry(QRect(420, 70, 1041, 211))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 50, 121, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(420, 330, 156, 25))
        font1 = QFont()
        font1.setPointSize(16)
        self.label_4.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 90, 101, 16))
        self.label.setFont(font)
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(30, 340, 38, 20))
        self.spinBox.setFont(font)
        self.int_up_link = QLineEdit(self.centralwidget)
        self.int_up_link.setObjectName(u"int_up_link")
        self.int_up_link.setGeometry(QRect(30, 280, 133, 22))
        self.int_up_link.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 25, 204, 25))
        self.label_3.setFont(font1)
        self.radioButton_4 = QRadioButton(self.centralwidget)
        self.buttonGroup.addButton(self.radioButton_4)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(260, 120, 94, 20))
        self.radioButton_4.setFont(font)
        self.radioButton_4.setCheckable(True)
        self.radioButton_8 = QRadioButton(self.centralwidget)
        self.buttonGroup.addButton(self.radioButton_8)
        self.radioButton_8.setObjectName(u"radioButton_8")
        self.radioButton_8.setGeometry(QRect(260, 160, 94, 20))
        self.radioButton_8.setFont(font)
        self.radioButton_8.setCheckable(True)
        self.radioButton_16 = QRadioButton(self.centralwidget)
        self.buttonGroup.addButton(self.radioButton_16)
        self.radioButton_16.setObjectName(u"radioButton_16")
        self.radioButton_16.setGeometry(QRect(260, 200, 97, 20))
        self.radioButton_16.setFont(font)
        self.radioButton_16.setCheckable(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 50, 111, 16))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 340, 121, 16))
        self.label_9.setFont(font)
        self.radioButton_32 = QRadioButton(self.centralwidget)
        self.buttonGroup.addButton(self.radioButton_32)
        self.radioButton_32.setObjectName(u"radioButton_32")
        self.radioButton_32.setGeometry(QRect(260, 240, 97, 20))
        self.radioButton_32.setFont(font)
        self.radioButton_32.setCheckable(True)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 430, 381, 61))
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.checkBoxNat = QCheckBox(self.centralwidget)
        self.checkBoxNat.setObjectName(u"checkBoxNat")
        self.checkBoxNat.setGeometry(QRect(210, 380, 141, 17))
        self.checkBoxNat.setFont(font)
        self.checkBoxJump = QCheckBox(self.centralwidget)
        self.checkBoxJump.setObjectName(u"checkBoxJump")
        self.checkBoxJump.setGeometry(QRect(30, 380, 141, 17))
        self.checkBoxJump.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        QWidget.setTabOrder(self.Rede_priv, self.Rede_pub)
        QWidget.setTabOrder(self.Rede_pub, self.int_up_link)
        QWidget.setTabOrder(self.int_up_link, self.radioButton_4)
        QWidget.setTabOrder(self.radioButton_4, self.radioButton_8)
        QWidget.setTabOrder(self.radioButton_8, self.radioButton_16)
        QWidget.setTabOrder(self.radioButton_16, self.radioButton_32)
        QWidget.setTabOrder(self.radioButton_32, self.radioButton_64)
        QWidget.setTabOrder(self.radioButton_64, self.pushButton)
        QWidget.setTabOrder(self.pushButton, self.inicio_0)
        QWidget.setTabOrder(self.inicio_0, self.Regras_jumping)
        QWidget.setTabOrder(self.Regras_jumping, self.Regras_nat)
        QWidget.setTabOrder(self.Regras_nat, self.inicio_1024)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"INTERFACE UPLINK", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"REDE P\u00daBLICA", None))
        self.inicio_1024.setText(QCoreApplication.translate("MainWindow", u"INICAR NA PORTA 1024", None))
        self.radioButton_64.setText(QCoreApplication.translate("MainWindow", u"64 CLIENTES", None))
        self.inicio_0.setText(QCoreApplication.translate("MainWindow", u"INICIAR NA PORTA 0", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"CLIENTES POR IP P\u00daBLICO", None))
        self.Rede_priv.setText("")
        self.Rede_priv.setPlaceholderText(QCoreApplication.translate("MainWindow", u"100.64.0.0/22", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"N\u00c3O RECOMENDADO", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"REGRAS DE NAT", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"REDE PRIVADA", None))
        self.int_up_link.setPlaceholderText(QCoreApplication.translate("MainWindow", u"sfp-sfpplus1 / VLAN_4096", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"REGRAS DE JUMPING", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"4  CLIENTES", None))
        self.radioButton_8.setText(QCoreApplication.translate("MainWindow", u"8  CLIENTES", None))
        self.radioButton_16.setText(QCoreApplication.translate("MainWindow", u"16 CLIENTES", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"    RECOMENDADO", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"INICIO DA CHAIN", None))
        self.radioButton_32.setText(QCoreApplication.translate("MainWindow", u"32 CLIENTES", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"GERAR", None))
        self.checkBoxNat.setText(QCoreApplication.translate("MainWindow", u"NAT DESABILITADO", None))
        self.checkBoxJump.setText(QCoreApplication.translate("MainWindow", u"JUMP DESABILITADO", None))
    # retranslateUi

